alpine: Add support for armv7 Alpine Linux
product-os/python-build pull request #8
Opened 2018-11-16 17:25 UTC by nghiant2710

binary built from Debian Jessie will be compatible with OpenSSl1.0.x and
from Debian Stretch will be compatible with OpenSSL1.1.x

Signed-off-by: Trong Nghia Nguyen <nghiant2710@gmail.com>

2018-12-07 03:30 UTC, petrosagg requested changes

2018-12-07 03:30 UTC, petrosagg commented on build.sh
>  curl -SL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" -o python.tar.xz
You should download the key using its keyid from a key server here

2018-12-07 20:47 UTC, nghiant2710 commented on build.sh
>  curl -SL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" -o python.tar.xz
@petrosagg all the keys used to verify are downloaded before https://github.com/balena-io/python-build/blob/5128a9d14375a2a4101facada36b4545d0a55898/build.sh#L3-L6

2019-03-29 14:14 UTC, shaunmulligan approved these changes

2019-03-29 16:19 UTC, merged